name: Automerge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
        # ref: https://github.com/marketplace/actions/merge-pull-requests-automerge-action#configuration
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "automerge"
          MERGE_FILTER_AUTHOR: "nwithan8"
          MERGE_REQUIRED_APPROVALS: 0
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "automatic"
          MERGE_DELETE_BRANCH: "true"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          MERGE_ERROR_FAIL: "true"
